### ISSUE TITLE
Assert crashes app

### ISSUE THREAD

**Issue by zackliston** [mRs-/HexColors#11]
Line 33 in HexColor.m
`assert(7 == hexString.length || 4 == hexString.length);`

This crashes the app if the hexString is not the right length. I'd be nice if it just provided a default color instead of crashing. My solution:

```
    if (7 != hexString.length && 4 != hexString.length) {
        NSString *defaultHex    = [NSString stringWithFormat:@"0xff"];
        unsigned defaultInt = [[self class] hexValueToUnsigned:defaultHex];
        
        HXColor *color = [HXColor colorWith8BitRed:defaultInt green:defaultInt blue:defaultInt alpha:1.0];
        return color;
    }
```

It's not perfect, but I think providing a wrong color is a much better experience than crashing the app. Also, I think error handling belongs inside that library rather than outside of it. 

Thanks

**Comment by mRs-** [comment]
prefixing will be in the next major release. breaking the current implementation
