### ISSUE TITLE
Cannot find interface declaration for 'NSColor'; did you mean 'NSCoder'?

### ISSUE THREAD

**Issue by HeliosDev** [mRs-/HexColors#13]
I am getting this error on compile while using HexColors and TSMessages along with about 20 more errors, all related to HXColor.

**Comment by SoundBlaster** [comment]
Minimum PCH content

    #ifdef __OBJC__
    #import <UIKit/UIKit.h>
    #import "HexColor.h"
    #endif

**Comment by HeliosDev** [comment]
Problem resurfaced with iOS8 project. Tried adding PrefixHeader.pch with both previous content and the minimum suggested by SoundBlaster to no avail. Can't use TSMessages anymore :-(

**Comment by mRs-** [comment]
iOS 8 only projects are default working with modules. If you use modules the PrefixHeader.pch is not necessary an more. You have to link the .pch in your build target.

**Comment by aporat** [comment]
after upgrading to xcode 6.3, I'm experiencing a similar issue in a Swift iOS project. the project will not compile.

I resolved it by importing `<UIKit/UIKit.h>` before `#import "HexColor.h"` inside the objc to swift bridging header:

```
//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//


#import <UIKit/UIKit.h>
#import "HexColor.h"
...
```

**Comment by mRs-** [comment]
got the same problem here. the main reason is that TARGET_IPHONE_SIMULATOR and TARGET_OS_IPHONE is linked in UIKit and we are depending on that for the OSX Support. Maybe not the best idea here ;)

Any suggestion to fix this?

**Comment by mRs-** [comment]
current solution in the example project: https://github.com/mRs-/HexColors/blob/develop/Classes/HexColor.h#L15

**Comment by aporat** [comment]
would including TargetConditionals.h in `#import "HexColor.h"` work for osx as well? http://stackoverflow.com/questions/24664649/conditional-compiling-of-objective-c-in-a-swift-project

**Comment by mRs-** [comment]
seems to work fine!

**Comment by mRs-** [comment]
@aporat does it work for you now without importing UIKit in the bridging header?

**Comment by aporat** [comment]
yeah, that solution works fine with swift projects (atleast for ios)
