### ISSUE TITLE
Use HexColors prefix/suffix for HXColor colorWith8BitRed:green:blue:alpha method

### ISSUE THREAD

**Issue by varkor** [mRs-/HexColors#23]
This method name is a common-enough choice that it conflicts with other pods (e.g. [MDCSwipeToChoose](https://github.com/modocache/MDCSwipeToChoose)), causing undefined behaviour and breaking various functionality. Please rename it to something unique so these issues can be avoided.

(This could well apply to other methods, but it was this one in particular that caused me problems.)

**Comment by mRs-** [comment]
Hand in a Pull Request and I will look into this.
