### ISSUE TITLE
Linking TapJoySDK causes +colorWithHexString: to always return nil

### ISSUE THREAD

**Issue by cameronehrlich** [mRs-/HexColors#27]
I think they are swizzleing `+colorWithHexString:` internally or something.  I don't think there is anything we can do in this repo to solve this except go yell at https://twitter.com/tapjoy.

The work around I found was to use `+colorWithHexString:alpha:`.

**Comment by mRs-** [comment]
In 3.0.0 of HexColors i will prefix the method calls with hx_colorWithHexString and the problem is solved then ;)

**Comment by cameronehrlich** [comment]
Nice!
(TapJoy is awful!)

**Comment by mRs-** [comment]
At the meantime you can use this: https://github.com/mRs-/HexColors/pull/26

**Comment by cameronehrlich** [comment]
:+1:

**Comment by mRs-** [comment]
Just pushed version 3.0.0 to cocoapods, feel free to use it

**Comment by cameronehrlich** [comment]
You rock.
