### ISSUE TITLE
Move to Swift

### ISSUE THREAD

**Issue by mRs-** [mRs-/HexColors#28]
I want to rewrite the complete library in swift for easier support in swift only projects. For this I will bump this up to version 4.0.0 and it can be API breaking. It will support iOS, tvOS, watchOS and OS X and it will be complete documented.
# ToDos
- [x] rewrite in swift
- [x] framework support
- [x] tvOS support
- [x] watchOS support
- [x] iOS support
- [x] OS X support
- [x] unit tests
- [x] complete documentation 
- [x] create README with legacy support

**Comment by billburgess** [comment]
+1

**Comment by billburgess** [comment]
Do you plan to create a brand new repo for this or just make it Swift only going forward.

**Comment by mRs-** [comment]
That's a real good question. IMHO it would be the best way to move in this repo to swift, because it's just natural to do this here and swift is the next step in the ecosystem. 

For objective-c I would to generate a explanation in the README file, how to get there. It's easy to change the Version on CocoaPods to get there and at the moment this small lib is really stable for objective-c.

**Comment by billburgess** [comment]
Cocopods at least will allow you a ton of movement from a 3.x updates to 4.x updates. Anyone wanting to use Obj-C can just set the dependency to less than 4, and Swift only can target the latest.

**Comment by mRs-** [comment]
There are news! Yay! 

Try https://github.com/mRs-/HexColors/tree/swift-3.0 for Swift 3.0 support

**Comment by billburgess** [comment]
Hey Marius, great job on the Swift rewrite. I'll take a look and pull into one of my Swift projects. I'll keep you posted.

**Comment by mRs-** [comment]
Any news @billburgess

**Comment by mRs-** [comment]
Opened Pull request: https://github.com/mRs-/HexColors/pull/39

**Comment by billburgess** [comment]
I am still in the process of converting one of my Swift projects to 3.0. I did review the code and looks great. Very Swifty 3 point oh-y. ;) Once I get in to day to day use after conversion, I'll be sure to send any PR's your way if needed.
