### ISSUE TITLE
Add cache for HexColors

### ISSUE THREAD

**Issue by littlewu0** [mRs-/HexColors#38]
Hello, Marius Landwehr

I think it's very useful to add a global cache for HexColors, like NSColor or UIColor, and I add it myself.

What do you think about it ?

Best regards!

**Comment by mRs-** [comment]
sounds like a good and easy to implement thing

**Comment by mRs-** [comment]
IMHO it's up to the user of this library to cache colors. It's easy to implement tho, you could just save it in a Dictonary.
