### ISSUE TITLE
Support Objective-C

### ISSUE THREAD

**Issue by yishuiliunian** [mRs-/HexColors#41]
Please Support Objective-C. i use cocoapods to install this podspec, but it say must use "user_framework", when i add it ,some podspec contains static library will not be installed.

**Comment by mRs-** [comment]
It's not possible to not enable `use_frameworks!` see the discussion in https://github.com/CocoaPods/CocoaPods/issues/3839

**Comment by cameronehrlich** [comment]
I don't mean to nag, but I do think that backwards compatibility with Objc would be greatly appreciated by many...

**Comment by mRs-** [comment]
@cameronehrlich you can still install the 4.X version of HexColors for full objc support

**Comment by cameronehrlich** [comment]
@mRs- that's what I'm doing now, but I hate seeing this:
```
% pod outdated
Updating spec repo `master`
Analyzing dependencies
The following pod updates are available:
- HexColors 4.0.0 -> 4.0.0 (latest version 5.0.0)
```

haha, I guess I should get over it... 😄 

In case anyone is/was unsure of how to do this:
```
pod 'HexColors', :git => 'git@github.com:mRs-/HexColors.git', :tag => '4.0.0'
```

**Comment by mRs-** [comment]
The main Problem is that as long as you are referring it to use it without use_framework there is no way around this :(

**Comment by cameronehrlich** [comment]
I am using `use_frameworks!` though...? I might be confused...
