### ISSUE TITLE
Xcode 9.1 beta 2 warning

### ISSUE THREAD

**Issue by StuSchwartz** [mRs-/HexColors#47]
I am getting a new warning when moved to Xcode 9.1 beta 2 

Swift Compiler Warning
HexColors.swift:74:21: 'characters' is deprecated: Please use String or Substring directly

**Comment by mRs-** [comment]
Didn't checked out the beta till now

**Comment by ems305** [comment]
PR #48 submitted

**Comment by mRs-** [comment]
Thanks to @ems305 fixed on the master branch.
